### ISSUE TITLE
Can It intergrate with Dominus77/SyntaxHighlighter

### ISSUE THREAD

**Issue by polinwei** [Dominus77/yii2-highlight-plugin#1]
I write document in tinymce . If I insert php code through `SH4TinyMCE - CODE Editor` ,  The line number can not show out.

`<pre class="brush:php;auto-links:false;toolbar:false" contenteditable="false" data-mce-selected="1">&lt;?= $form-....`

If I using `Dominus77/SyntaxHighlighter` then it is workable.

**Comment by polinwei** [comment]
Sorry !! Forget !! I think the both is different.

**Comment by polinwei** [comment]
In the windows `Insert/Edit Code Sample`  , How add more language ? like `SQL , Perl...`

**Comment by Dominus77** [comment]
Hi!
In what extension?
For [Codesample](https://www.tinymce.com/docs/plugins/codesample/) right in the settings of TinyMce.

**Comment by polinwei** [comment]
Hi Sir:
I also found out the same page . thanks
