### ISSUE TITLE
The higlighter doesn't work in gridview unless reload.

### ISSUE THREAD

**Issue by pkjoshi** [Dominus77/yii2-highlight-plugin#2]
Hi
I have downloaded and integrated the plugin in my setup.
only issue I see, which is bothering me is like -
If open grid-view the first page shows the high-lighter just fine, but when I navigate to any page in gridview - the highlighter doesn't work, unless I reload.
same issue is like when I open view from grid-view and then back to grid-view using breadcrumbs, even the first page is missing the highlighter.

How I can fix it.

**Comment by Dominus77** [comment]
Hi, I suspect you are using pjax?

**Comment by Dominus77** [comment]
In this case, you need to reinitialize the plugin.

Example:

```php
<?php
//...
\dominus77\highlight\Plugin::$options = [
    'theme' => 'paraiso-dark',// Styles
];
\dominus77\highlight\Plugin::register($this);

$js = "
    $(document).on('ready pjax:success', function() {       
       $('pre code').each(function(i, block) {
            hljs.highlightBlock(block);
       });
    });
";
$this->registerJs($js, \yii\web\View::POS_END);
?>

<?php Pjax::begin([
    'id' => 'pjax-container',
    'enablePushState' => false,
    'timeout' => 5000,
]); ?>
    <pre><code class="php">echo "Hello World!";</code></pre>
<!-- ... -->
<?php Pjax::end(); ?>
```
https://github.com/Dominus77/yii2-highlight-plugin#custom-init

**Comment by pkjoshi** [comment]
Thanks Dominus,
Yes I am using Pjax. but your suggestion works perfect.

**Comment by Dominus77** [comment]
So that's great)
